# Generated by Django 5.0 on 2023-12-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_pacients_patients_doctors_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='consult',
            field=models.BooleanField(default=False),
        ),
    ]
